version: '3.1'
services:
  backend-for-ai:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"

  database:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=password

  database-adminer:
    image: adminer
    restart: always
    porst:
      - 8080:8080
